/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reto5;

import java.util.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jhonj
 */
public class reto5 extends javax.swing.JFrame {
    
    String historialTexto = "";
    ArrayList<Paciente> pacientes = new ArrayList<>();
    ArrayList<Medico> medicos = new ArrayList<>();
    String  linea; int val= 0; int mayor = 0; int menor = 0;
    String [] enfermedades = new String[] {"cancer", "cardiovasculares", 
        "respiratorias", "cerebrovasculares", "hipertension", "diabetes"};
    int [] conteoEnfermedades = new int []{0,0,0,0,0,0};
    List<String> nombreEps = new ArrayList<String>(); 
    List<Integer> conteoEps = new ArrayList<Integer>();  
    List<List<String>> pacientesAsignadosMedico = new ArrayList<>();
    
    
    /**
     * Creates new form reto3
     */
    public reto5() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(232, 249, 248));
        limpiarListaMedico();
        limpiarListadoMedicos();
        limpiarListaPaciente();
        limpiarListaMostrarPaciente();
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelPaciente = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        labelCedula = new javax.swing.JLabel();
        textCedula = new javax.swing.JTextField();
        labelEdad = new javax.swing.JLabel();
        textEdad = new javax.swing.JTextField();
        labelCiudad = new javax.swing.JLabel();
        textCiudad = new javax.swing.JTextField();
        labelEps = new javax.swing.JLabel();
        textEps = new javax.swing.JTextField();
        labelEnfermedad = new javax.swing.JLabel();
        textEnfermedad = new javax.swing.JTextField();
        buttonIngresar = new javax.swing.JButton();
        jPanelMedico = new javax.swing.JPanel();
        labelNombreM = new javax.swing.JLabel();
        labelCedulaM = new javax.swing.JLabel();
        textNombreM = new javax.swing.JTextField();
        textCedulaM = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListPacientesMedico = new javax.swing.JList<>();
        labelSeleccionarPacientes = new javax.swing.JLabel();
        jButtonGuardaM = new javax.swing.JButton();
        jButtonAsignarPacientes = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListMedicos = new javax.swing.JList<>();
        labelSeleccionarPacientes1 = new javax.swing.JLabel();
        jPanelResultados = new javax.swing.JPanel();
        labelPacientesMedicos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        datosIngresados = new javax.swing.JTextArea();
        labelSalidas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextFieldAdultos = new javax.swing.JTextArea();
        buttonProcesar = new javax.swing.JButton();
        buttonMostrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldMasEnf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMenosEnf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEps = new javax.swing.JTextField();
        buttonPacientesMedico = new javax.swing.JButton();
        labelDatosIngresados = new javax.swing.JLabel();
        jComboBoxMedico = new javax.swing.JComboBox<>();
        labelDatosIngresados2 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListMostrasPacientesMedico = new javax.swing.JList<>();
        labelInvEnf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reto 3 Jhon Jairo Vega Diaz");

        labelNombre.setText("Nombre");

        textNombre.setActionCommand("<Not Set>");

        labelCedula.setText("Cédula");
        labelCedula.setToolTipText("");

        textCedula.setActionCommand("<Not Set>");

        labelEdad.setText("Edad");
        labelEdad.setToolTipText("");

        textEdad.setActionCommand("<Not Set>");

        labelCiudad.setText("Ciudad");
        labelCiudad.setToolTipText("");

        textCiudad.setActionCommand("<Not Set>");

        labelEps.setText("EPS");
        labelEps.setToolTipText("");

        textEps.setActionCommand("<Not Set>");

        labelEnfermedad.setText("Enfermedad diagnosticada");
        labelEnfermedad.setToolTipText("");

        textEnfermedad.setActionCommand("<Not Set>");

        buttonIngresar.setText("Ingresar datos");
        buttonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPacienteLayout = new javax.swing.GroupLayout(jPanelPaciente);
        jPanelPaciente.setLayout(jPanelPacienteLayout);
        jPanelPacienteLayout.setHorizontalGroup(
            jPanelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelPacienteLayout.createSequentialGroup()
                        .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonIngresar)
                    .addGroup(jPanelPacienteLayout.createSequentialGroup()
                        .addGroup(jPanelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textEps, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEps, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPacienteLayout.createSequentialGroup()
                        .addComponent(textEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textEnfermedad)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanelPacienteLayout.setVerticalGroup(
            jPanelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPacienteLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPacienteLayout.createSequentialGroup()
                        .addGroup(jPanelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCiudad)
                            .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPacienteLayout.createSequentialGroup()
                        .addComponent(labelEps)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textEps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPacienteLayout.createSequentialGroup()
                        .addGroup(jPanelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEdad)
                            .addComponent(labelEnfermedad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(buttonIngresar)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Paciente", jPanelPaciente);

        labelNombreM.setText("Nombre");

        labelCedulaM.setText("Cédula");
        labelCedulaM.setToolTipText("");

        textNombreM.setActionCommand("<Not Set>");

        textCedulaM.setActionCommand("<Not Set>");

        jScrollPane3.setViewportView(jListPacientesMedico);

        labelSeleccionarPacientes.setText("Seleccionar pacientes");

        jButtonGuardaM.setText("Guardar");
        jButtonGuardaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardaMActionPerformed(evt);
            }
        });

        jButtonAsignarPacientes.setText("Asignar pacientes a médico");
        jButtonAsignarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsignarPacientesActionPerformed(evt);
            }
        });

        jListMedicos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListMedicos.setToolTipText("");
        jScrollPane5.setViewportView(jListMedicos);

        labelSeleccionarPacientes1.setText("Seleccionar médico");

        javax.swing.GroupLayout jPanelMedicoLayout = new javax.swing.GroupLayout(jPanelMedico);
        jPanelMedico.setLayout(jPanelMedicoLayout);
        jPanelMedicoLayout.setHorizontalGroup(
            jPanelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMedicoLayout.createSequentialGroup()
                        .addComponent(labelNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelCedulaM, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMedicoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonAsignarPacientes)
                        .addGap(186, 186, 186))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMedicoLayout.createSequentialGroup()
                        .addGroup(jPanelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelMedicoLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(labelSeleccionarPacientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelSeleccionarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textCedulaM, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))))
            .addGroup(jPanelMedicoLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jButtonGuardaM)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelMedicoLayout.setVerticalGroup(
            jPanelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMedicoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCedulaM, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCedulaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jButtonGuardaM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSeleccionarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSeleccionarPacientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(24, 24, 24)
                .addComponent(jButtonAsignarPacientes)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Médico", jPanelMedico);

        labelPacientesMedicos.setText("Pacientes del médico seleccionado");
        labelPacientesMedicos.setToolTipText("");

        datosIngresados.setColumns(20);
        datosIngresados.setRows(5);
        jScrollPane2.setViewportView(datosIngresados);

        labelSalidas.setText("Pacientes categoría Adulto");
        labelSalidas.setToolTipText("");

        jTextFieldAdultos.setColumns(20);
        jTextFieldAdultos.setRows(5);
        jScrollPane1.setViewportView(jTextFieldAdultos);

        buttonProcesar.setText("Procesar datos");
        buttonProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProcesarActionPerformed(evt);
            }
        });

        buttonMostrar.setText("Mostrar pacientes");
        buttonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMostrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Enfermedad que más se presenta:");

        jLabel2.setText("Enfermedad que menos se presenta:");

        jLabel3.setText("EPS con mayor número de pacientes");

        buttonPacientesMedico.setText("Pacientes del médico");
        buttonPacientesMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPacientesMedicoActionPerformed(evt);
            }
        });

        labelDatosIngresados.setText("Datos Ingresados de los pacientes");
        labelDatosIngresados.setToolTipText("");

        labelDatosIngresados2.setText("Seleccionar médico");
        labelDatosIngresados2.setToolTipText("");

        jScrollPane6.setViewportView(jListMostrasPacientesMedico);

        javax.swing.GroupLayout jPanelResultadosLayout = new javax.swing.GroupLayout(jPanelResultados);
        jPanelResultados.setLayout(jPanelResultadosLayout);
        jPanelResultadosLayout.setHorizontalGroup(
            jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultadosLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(buttonMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(jPanelResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDatosIngresados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelResultadosLayout.createSequentialGroup()
                        .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPacientesMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelResultadosLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(buttonPacientesMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDatosIngresados2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMenosEnf, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEps, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldMasEnf, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );
        jPanelResultadosLayout.setVerticalGroup(
            jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultadosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonProcesar)
                    .addComponent(buttonMostrar))
                .addGap(11, 11, 11)
                .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelResultadosLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelResultadosLayout.createSequentialGroup()
                        .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(labelDatosIngresados))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMasEnf, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMenosEnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelResultadosLayout.createSequentialGroup()
                        .addComponent(labelDatosIngresados2)
                        .addGap(7, 7, 7)
                        .addComponent(jComboBoxMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(buttonPacientesMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPacientesMedicos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelResultadosLayout.createSequentialGroup()
                        .addComponent(labelSalidas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Resultados", jPanelResultados);

        labelInvEnf.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        labelInvEnf.setText("Investigación de enfermedades");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelInvEnf)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelInvEnf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIngresarActionPerformed
        // TODO add your handling code here:
        agregarDatos();
        
    }//GEN-LAST:event_buttonIngresarActionPerformed

        private void limpiarListaMedico() {
        DefaultListModel modeloVacio1 = new DefaultListModel();
        jListMedicos.setModel(modeloVacio1);
    }
        
        private void limpiarListaPaciente() {
        DefaultListModel modeloVacio2 = new DefaultListModel();
        jListPacientesMedico.setModel(modeloVacio2);
    }
    
    private void limpiarListaMostrarPaciente() {
        DefaultListModel modeloVacio3 = new DefaultListModel();
        jListMostrasPacientesMedico.setModel(modeloVacio3);
    }
        
        
    private void limpiarListadoMedicos() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        jComboBoxMedico.setModel(modelo);
    }    
        
    
    
    /**
     * Crear salida de datos
     * @param evt 
     */
    
    private void buttonProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProcesarActionPerformed
        // TODO add your handling code here:

        String salida_enfermedad_mayor;
        String salida_enfermedad_menor;
        String salida_eps;
        String salida_adulto = "";

        for (int j = 0; j < enfermedades.length; j++) {
            if (conteoEnfermedades[j] > val) {
                val = conteoEnfermedades[j];
                mayor = j;
            }
        }
        for (int j = 0; j < enfermedades.length; j++) {
            if (conteoEnfermedades[j] < val) {
                val = conteoEnfermedades[j];
                menor = j;
            }
        }
        salida_enfermedad_mayor=enfermedades[mayor];
        salida_enfermedad_menor=enfermedades[menor];

        val=0;
        for (int j = 0; j < nombreEps.size(); j++) {
            if (conteoEps.get(j) > val) {
                val = conteoEps.get(j);
                mayor = j;
            }
        }
        salida_eps=nombreEps.get(mayor);

        for (int i = 0; i < pacientes.size() ; i++) {
            if (pacientes.get(i).clasificarEdad().equals("adulto")){
                salida_adulto+=pacientes.get(i).getNombreCompleto()+ " " + pacientes.get(i).getNumeroCedula()+"\n";
            }
        }
        
        jTextFieldMasEnf.setText(salida_enfermedad_mayor);
        jTextFieldMenosEnf.setText(salida_enfermedad_menor);
        jTextFieldEps.setText(salida_eps);
        jTextFieldAdultos.setText(salida_adulto);

    }//GEN-LAST:event_buttonProcesarActionPerformed

    private void mostrarPacienteMedico(){
        
       Medico medicoPaciente = new Medico();
       medicoPaciente.setPacientesAsMedico(pacientesAsignadosMedico);
       List<String> pacientesMeLista = medicoPaciente.pacientes(jComboBoxMedico.getSelectedItem().toString());
       DefaultListModel pacienteLista = new DefaultListModel ();
       pacienteLista.addAll(pacientesMeLista);
       // Actualizar los valores de la lista
       jListMostrasPacientesMedico.setModel(pacienteLista);
        
    }
            
    private void buttonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMostrarActionPerformed
        // TODO add your handling code here:
        datosIngresados.setText(historialTexto);
    }//GEN-LAST:event_buttonMostrarActionPerformed

    private void buttonPacientesMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPacientesMedicoActionPerformed
        // TODO add your handling code here:
        mostrarPacienteMedico();
    }//GEN-LAST:event_buttonPacientesMedicoActionPerformed

    private void jButtonGuardaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardaMActionPerformed
        // TODO add your handling code here:
        agregarDatosMedico();
    }//GEN-LAST:event_jButtonGuardaMActionPerformed

    private void jButtonAsignarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsignarPacientesActionPerformed
        // TODO add your handling code here:
            if(jListMedicos.getSelectedIndex() != -1 && jListPacientesMedico .getSelectedIndex() != -1){
                String medicoPacientesSel = jListMedicos.getSelectedValue().toString();
                List<String> pacientesMedicoSel = new ArrayList<String>();
                pacientesMedicoSel.add(medicoPacientesSel);
                pacientesMedicoSel.addAll(jListPacientesMedico.getSelectedValuesList());
            int cont=0;
            for (int i = 0; i < pacientesAsignadosMedico.size() ; i++) {
                List<String> medico = pacientesAsignadosMedico.get(i);
                if (medico.get(0).equals(medicoPacientesSel)){                    
                    pacientesAsignadosMedico.set(i , pacientesMedicoSel);
                    JOptionPane.showMessageDialog(this, "Pacientes asignados"); 
                    cont=1;
                    }
                }
            if (cont==0){
                 pacientesAsignadosMedico.add(pacientesMedicoSel);
                 JOptionPane.showMessageDialog(this, "Pacientes asignados"); 
            }
            }else{
               JOptionPane.showMessageDialog(this, "Seleccionar un médico y por lo menos un paciente"); 
            }
        
    }//GEN-LAST:event_jButtonAsignarPacientesActionPerformed

    /**
     * Limpiar los datos de los campos de texto
     */
    private void limpiarTexto(){
        textNombre.setText("");
        textCiudad.setText("");
        textEps.setText("");
        textEnfermedad.setText("");
        textCedula.setText("");
        textEdad.setText("");
    }
         
        /**
     * Limpiar los datos de los campos de texto
     */
    private void limpiarTextoMedico(){
        textNombreM.setText("");
        textCedulaM.setText("");
    }
         

    /**
     * Agrega datos en el programa a partir del boton ingresar
     */
    private void agregarDatos(){
        
        String nombreCompleto = textNombre.getText().trim();
        String ciudad = textCiudad.getText().trim();
        String eps = textEps.getText().trim();
        String enfermedadDiagnosticada = textEnfermedad.getText().trim(); 
        
        if(!nombreCompleto.isBlank() && !ciudad.isBlank() 
                && !eps.isBlank() && !eps.isBlank()
                && !enfermedadDiagnosticada.isBlank()
                && !textCedula.getText().trim().isBlank() 
                && !textEdad.getText().trim().isBlank()) {
            if (textCedula.getText().trim().matches("[0-9]+")
                && textEdad.getText().trim().matches("[0-9]+") 
                && !textCedula.getText().trim().matches("[-]?\\.?")
                && !textEdad.getText().trim().matches("[-]?\\.?") ){
                    long numeroCedula = Long.parseLong(textCedula.getText().trim());
                    int edad = Integer.parseInt(textEdad.getText().trim());
                    String textoIngresado = nombreCompleto+" "+textCedula.getText()+" "
                            +textEdad.getText()+" "+ciudad+" "+eps+" "+enfermedadDiagnosticada+"\n";
                    historialTexto+=textoIngresado;                  
                    limpiarTexto();
                    
                    // Obtener los valores que tiene la lista actualmente
                    DefaultListModel pacienteLista = (DefaultListModel)jListPacientesMedico.getModel();
                    // Agregar el nuevo valor
                    pacienteLista.addElement(nombreCompleto + " " + numeroCedula);
                    // Actualizar los valores de la lista
                    jListPacientesMedico.setModel(pacienteLista);
                    
                    Paciente paciente = new Paciente(ciudad, eps, enfermedadDiagnosticada, nombreCompleto,numeroCedula, edad);
                    pacientes.add(paciente);
                    
                    for (int k = 0; (k < enfermedades.length); k++) {
                       if (enfermedades[k].equalsIgnoreCase(enfermedadDiagnosticada)){
                                conteoEnfermedades[k]++;
                           }
                       } 
                       if (nombreEps.contains(eps)){
                            for (int j = 0; j < nombreEps.size(); j++) {
                                if (nombreEps.get(j).equalsIgnoreCase(eps)){
                                conteoEps.set(j, conteoEps.get(j)+1);
                                }
                            }
                       }else{
                           nombreEps.add(eps);
                           conteoEps.add(1);
                       }

            }
            else{
                JOptionPane.showMessageDialog(this, "Ingresar solo números en la cedula y la edad, intentar de nuevo");
            }          
        }else{
            JOptionPane.showMessageDialog(this, "Diligenciar todos los campos, intentar de nuevo");                            
        }   
    }
        
    
    /**
     * Agrega datos en el programa a partir del boton ingresar
     */
    private void agregarDatosMedico(){
        String valor;
        String nombreCompleto = textNombreM.getText().trim();        
        if(!nombreCompleto.isBlank()) {
            if (textCedulaM.getText().trim().matches("[0-9]+")
                && !textCedulaM.getText().trim().matches("[-]?\\.?")){
                    long numeroCedula = Long.parseLong(textCedulaM.getText().trim());                
                    limpiarTextoMedico();
                    
                    Medico medico = new Medico(nombreCompleto,numeroCedula);
                    medicos.add(medico);
                    
                    valor= nombreCompleto + " " +numeroCedula;
                    
                    // Obtener los valores que tiene la lista actualmente
                    DefaultListModel medicoLista = (DefaultListModel)jListMedicos.getModel();
                    // Agregar el nuevo valor
                    medicoLista.addElement(valor);
                    // Actualizar los valores de la lista
                    jListMedicos.setModel(medicoLista);
                    // Obtener los valores que tiene la lista actualmente
                    DefaultComboBoxModel modelo = (DefaultComboBoxModel)jComboBoxMedico.getModel();
                    // Actualizar los valores que de la lista 
                    modelo.addElement(nombreCompleto + " " + numeroCedula);
                    // Mostrar los valores que de la lista 
                    jComboBoxMedico.setModel(modelo);
                    jComboBoxMedico.setSelectedIndex(-1);
                          
            }
            else{
                JOptionPane.showMessageDialog(this, "Ingresar solo números en la cedula, intentar de nuevo");
            }          
        }else{
            JOptionPane.showMessageDialog(this, "Diligenciar todos los campos, intentar de nuevo");                            
        }   
    }
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reto5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonIngresar;
    private javax.swing.JButton buttonMostrar;
    private javax.swing.JButton buttonPacientesMedico;
    private javax.swing.JButton buttonProcesar;
    private javax.swing.JTextArea datosIngresados;
    private javax.swing.JButton jButtonAsignarPacientes;
    private javax.swing.JButton jButtonGuardaM;
    private javax.swing.JComboBox<String> jComboBoxMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListMedicos;
    private javax.swing.JList<String> jListMostrasPacientesMedico;
    private javax.swing.JList<String> jListPacientesMedico;
    private javax.swing.JPanel jPanelMedico;
    private javax.swing.JPanel jPanelPaciente;
    private javax.swing.JPanel jPanelResultados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextFieldAdultos;
    private javax.swing.JTextField jTextFieldEps;
    private javax.swing.JTextField jTextFieldMasEnf;
    private javax.swing.JTextField jTextFieldMenosEnf;
    private javax.swing.JLabel labelCedula;
    private javax.swing.JLabel labelCedulaM;
    private javax.swing.JLabel labelCiudad;
    private javax.swing.JLabel labelDatosIngresados;
    private javax.swing.JLabel labelDatosIngresados2;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelEnfermedad;
    private javax.swing.JLabel labelEps;
    private javax.swing.JLabel labelInvEnf;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombreM;
    private javax.swing.JLabel labelPacientesMedicos;
    private javax.swing.JLabel labelSalidas;
    private javax.swing.JLabel labelSeleccionarPacientes;
    private javax.swing.JLabel labelSeleccionarPacientes1;
    private javax.swing.JTextField textCedula;
    private javax.swing.JTextField textCedulaM;
    private javax.swing.JTextField textCiudad;
    private javax.swing.JTextField textEdad;
    private javax.swing.JTextField textEnfermedad;
    private javax.swing.JTextField textEps;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textNombreM;
    // End of variables declaration//GEN-END:variables
}
